// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryLibrary.Data.Context;

#nullable disable

namespace RepositoryLibrary.Data.Migrations.RideReady
{
    [DbContext(typeof(RideReadyDbContext))]
    [Migration("20260601132415_RenamePhotoEntities")]
    partial class RenamePhotoEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositoryLibrary.Features.Bookings.Entities.Booking", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("WasPresent")
                        .HasColumnType("bit");

                    b.HasKey("LessonId", "UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserCreditLedgerEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreditsDelta")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseLineId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseLineId");

                    b.HasIndex("UserId", "LessonTypeId", "CreatedAtUtc");

                    b.ToTable("UserCreditLedgerEntries");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseLineId")
                        .HasColumnType("int");

                    b.Property<int>("PurchasedMonths")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseLineId");

                    b.HasIndex("UserId", "PeriodStart", "PeriodEnd", "Status");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserSubscriptionEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserSubscriptionId")
                        .HasColumnType("int");

                    b.Property<int>("WeeklyFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("UserSubscriptionEntitlements");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Horses.Entities.Horse", b =>
                {
                    b.Property<int>("HorseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorseId"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("HorseId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Horses.Entities.HorseFoto", b =>
                {
                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HorseId");

                    b.ToTable("HorseFotos");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<DateTime>("BeginOfLesson")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndOfLesson")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpots")
                        .HasColumnType("int");

                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.HasKey("LessonId");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.LessonHorse", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.HasKey("LessonId", "HorseId");

                    b.HasIndex("HorseId");

                    b.ToTable("LessonHorses");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.LessonProf", b =>
                {
                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LessonId", "UserId");

                    b.ToTable("LessonProfs");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Products.Entities.LessonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LessonTypes");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Products.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Products.Entities.ProductEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreditsGranted")
                        .HasColumnType("int");

                    b.Property<int>("LessonTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonTypeId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductEntitlements");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Purchases.Entities.Purchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MonthlyRecurringAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OneOffAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchasedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PurchasedAtUtc");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Purchases.Entities.PurchaseLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PurchaseId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SubscriptionMonths")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("SubscriptionPeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("SubscriptionPeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseId");

                    b.ToTable("PurchaseLines");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Schools.Entities.School", b =>
                {
                    b.Property<int>("SchoolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchoolId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CAE")
                        .HasColumnType("int");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SchoolCapacity")
                        .HasColumnType("int");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Schools.Entities.SchoolPhoto", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SchoolId");

                    b.ToTable("SchoolPhotos");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.EMUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CitizenNumber")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ImageAuthorized")
                        .HasColumnType("bit");

                    b.Property<bool>("InformationAuthorized")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SocialHealthNumber")
                        .HasColumnType("bigint");

                    b.Property<int>("TaxIdentificationNumber")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EMUser");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.SchoolUser", b =>
                {
                    b.Property<int>("SchoolId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SchoolId", "UserId");

                    b.ToTable("SchoolUsers");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.UserHorse", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "HorseId");

                    b.HasIndex("HorseId");

                    b.ToTable("UserHorses");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.UserPhoto", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Bookings.Entities.Booking", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Lessons.Entities.Lesson", "Lesson")
                        .WithMany("Bookings")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserCreditLedgerEntry", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.LessonType", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RepositoryLibrary.Features.Purchases.Entities.PurchaseLine", "PurchaseLine")
                        .WithMany()
                        .HasForeignKey("PurchaseLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LessonType");

                    b.Navigation("Product");

                    b.Navigation("PurchaseLine");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserSubscription", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Purchases.Entities.PurchaseLine", "PurchaseLine")
                        .WithMany()
                        .HasForeignKey("PurchaseLineId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Product");

                    b.Navigation("PurchaseLine");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserSubscriptionEntitlement", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.LessonType", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Entitlements.Entities.UserSubscription", "UserSubscription")
                        .WithMany("Entitlements")
                        .HasForeignKey("UserSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Horses.Entities.Horse", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Schools.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Horses.Entities.HorseFoto", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Horses.Entities.Horse", "Horse")
                        .WithOne("HorseFoto")
                        .HasForeignKey("RepositoryLibrary.Features.Horses.Entities.HorseFoto", "HorseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.Lesson", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.LessonType", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Schools.Entities.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("School");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.LessonHorse", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Horses.Entities.Horse", "Horse")
                        .WithMany("LessonHorses")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Lessons.Entities.Lesson", "Lesson")
                        .WithMany("LessonHorses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.LessonProf", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Lessons.Entities.Lesson", "Lesson")
                        .WithMany("LessonProfs")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Products.Entities.ProductEntitlement", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.LessonType", "LessonType")
                        .WithMany()
                        .HasForeignKey("LessonTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Products.Entities.Product", "Product")
                        .WithMany("Entitlements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LessonType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Purchases.Entities.PurchaseLine", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Products.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepositoryLibrary.Features.Purchases.Entities.Purchase", "Purchase")
                        .WithMany("Lines")
                        .HasForeignKey("PurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Schools.Entities.SchoolPhoto", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Schools.Entities.School", "School")
                        .WithOne("SchoolPhoto")
                        .HasForeignKey("RepositoryLibrary.Features.Schools.Entities.SchoolPhoto", "SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.SchoolUser", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Schools.Entities.School", "School")
                        .WithMany("SchoolUsers")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.UserHorse", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Horses.Entities.Horse", "Horse")
                        .WithMany("UserHorses")
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.UserPhoto", b =>
                {
                    b.HasOne("RepositoryLibrary.Features.Users.Entities.EMUser", "User")
                        .WithOne("UserPhoto")
                        .HasForeignKey("RepositoryLibrary.Features.Users.Entities.UserPhoto", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Entitlements.Entities.UserSubscription", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Horses.Entities.Horse", b =>
                {
                    b.Navigation("HorseFoto");

                    b.Navigation("LessonHorses");

                    b.Navigation("UserHorses");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Lessons.Entities.Lesson", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("LessonHorses");

                    b.Navigation("LessonProfs");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Products.Entities.Product", b =>
                {
                    b.Navigation("Entitlements");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Purchases.Entities.Purchase", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Schools.Entities.School", b =>
                {
                    b.Navigation("SchoolPhoto");

                    b.Navigation("SchoolUsers");
                });

            modelBuilder.Entity("RepositoryLibrary.Features.Users.Entities.EMUser", b =>
                {
                    b.Navigation("UserPhoto");
                });
#pragma warning restore 612, 618
        }
    }
}
